name: wlist_site
description: "The site of wlist."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ^3.8.1
  flutter: ^3.32.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true