name: wlist_site
description: "The site of wlist."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ^3.8.1
  flutter: ^3.32.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/platforms/
flutter_intl:
  enabled: true