name: Build

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Install intl
        run: flutter pub global activate intl_utils

      - name: Generate intl codes
        run: flutter pub global run intl_utils:generate

      - name: Build Web App
        run: flutter build web --release

      - name: Hash web
        run: |
          cargo install flutter_web_hasher
          flutter_web_hasher --skip index.html --skip 404.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wlist_site
          path: ./build/web
